version: '3'
services:
  react-app:
    build: . # React 애플리케이션의 Dockerfile 위치
    ports:
      - "3000:80"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - react-app
